---
- name: download
  become: yes
  become_user: root
  get_url:
    url: '{{calicoctl_url}}'
    dest: '{{calicoctl_target}}'
    mode: 0755
    checksum: '{{calicoctl_checksum}}'

- name: link
  become: yes
  become_user: root
  file:
    src: '{{calicoctl_target}}'
    dest: '{{calicoctl_link}}'
    state: link
